---

- name: pull-install | Install requirements
  apt: pkg={{item}}
  with_items: [git, cron, logrotate, python-software-properties]

- name: pull-install | Add ansible ppa
  apt_repository: repo={{pull_ansible_ppa}} update_cache=yes
  when: pull_install_ansible

- name: pull-install | Install ansible from APT
  apt: pkg=ansible state=latest update_cache=yes
  when: pull_install_ansible and pull_install_deb

- name: pull-install | Install ansible from PIP
  pip: name=ansible==2.8.6 state=forcereinstall
  when: pull_install_ansible and not pull_install_deb

- name: pull-install | Install mailutils
  apt: pkg=mailutils
  when: pull_mail_to != ""
